version: "3.9"
     
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - ./var/postgres-data:/data/postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    command: redis-server --requirepass devPassword
    volumes:
      - ./var/redis-data:/data
    ports:
     - "6379:6379"
